// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRng1DVWu4tqbYc6lDo0JGCNfZnzVkvf8',
    appId: '1:478869567626:web:f907e0bff189a63c13d573',
    messagingSenderId: '478869567626',
    projectId: 'jarnama-example',
    authDomain: 'jarnama-example.firebaseapp.com',
    storageBucket: 'jarnama-example.appspot.com',
    measurementId: 'G-CR5T4DZCRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpM-vJqNM2cXAE9FF_bUVar2GDolYQMeY',
    appId: '1:478869567626:android:ab3dcdbe41ac538213d573',
    messagingSenderId: '478869567626',
    projectId: 'jarnama-example',
    storageBucket: 'jarnama-example.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPeuBktqy2wEotHdE3PJM9B-NBYgUeotU',
    appId: '1:478869567626:ios:ca701b7ec2d0c9cc13d573',
    messagingSenderId: '478869567626',
    projectId: 'jarnama-example',
    storageBucket: 'jarnama-example.appspot.com',
    iosClientId: '478869567626-0oi1cqqi75pn590ma8h5u9kod816loqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaExample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPeuBktqy2wEotHdE3PJM9B-NBYgUeotU',
    appId: '1:478869567626:ios:ca701b7ec2d0c9cc13d573',
    messagingSenderId: '478869567626',
    projectId: 'jarnama-example',
    storageBucket: 'jarnama-example.appspot.com',
    iosClientId: '478869567626-0oi1cqqi75pn590ma8h5u9kod816loqt.apps.googleusercontent.com',
    iosBundleId: 'com.example.jarnamaExample',
  );
}
